# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 管理员1001登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "account": "1001",
  "password": "1001"
}

###

# 用户登录
# token: ea65098d334033f3391d50c76686329fc4dac73cee35367d63e3958d71c9c19486027abb63408656e66826c52c5ee734
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "account": "2001",
  "password": "123456"
}

###